language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - "git submodule update --init --recursive"

before_script:
  - "phpenv rehash"
  - "composer install"

script: "vendor/bin/phing test"

notifications:
  irc:
    channels:
      - "irc.freenode.org#kohana"
    template:
      - "%{repository}/%{branch} (%{commit}) - %{author}: %{message}"
      - "Build details: %{build_url}"
  email: false
